<a href="https://colab.research.google.com/github/MrPraphul/Numby-pandas/blob/main/NumPy_Pandas_Assessment_Praphul.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd


#Q1
arr = np.array([10, 20, 30, 40, 50])

print("Q1")
print("Array:", arr)
print("Shape:", arr.shape)
print("Data Type:", arr.dtype)

print("")

Q1
Array: [10 20 30 40 50]
Shape: (5,)
Data Type: int64

In [3]:
#Q2
arr = np.array([5, 10, 15, 20, 25])

print("Q2")
print("Add 5:", arr + 5)
print("Multiply by 2:", arr * 2)

print("")#

Q2
Add 5: [10 15 20 25 30]
Multiply by 2: [10 20 30 40 50]

In [4]:
#Q3
arr = np.array([12, 15, 18, 20, 25, 30])

print("Q3")
print("Mean:", np.mean(arr))
print("Median:", np.median(arr))
print("Minimum:", np.min(arr))
print("Maximum:", np.max(arr))
print("Standard Deviation:", np.std(arr))

print("")

Q3
Mean: 20.0
Median: 19.0
Minimum: 12
Maximum: 30
Standard Deviation: 6.027713773341708

In [5]:
#Q4
arr = np.array([10, 25, 30, 45, 50, 65, 70])

print("Q4")
print(arr[arr > 40])

print("")

Q4
[45 50 65 70]

In [6]:
#Q5
df = pd.DataFrame({
    "Name": ["Anu", "Rahul", "Meera", "Arun"],
    "Age": [21, 22, 20, 23],
    "Score": [85, 72, 91, 68]
})

print("Q5")
print(df)

print("")

Q5
    Name  Age  Score
0    Anu   21     85
1  Rahul   22     72
2  Meera   20     91
3   Arun   23     68

In [7]:
#Q6
print("Q6")

print("Name and Score:")
print(df[["Name", "Score"]])

print("Meera's record:")
print(df[df["Name"] == "Meera"])

print("")

Q6
Name and Score:
    Name  Score
0    Anu     85
1  Rahul     72
2  Meera     91
3   Arun     68
Meera's record:
    Name  Age  Score
2  Meera   20     91

In [8]:
#Q7
print("Q7")
print(df[df["Score"] > 75])

print("")

Q7
    Name  Age  Score
0    Anu   21     85
2  Meera   20     91

In [9]:
#Q8
print("Q8")

print("Rows and Columns:")
print(df.shape)

print("Column Names:")
print(df.columns)

print("Data Types:")
print(df.dtypes)

print("Statistical Summary:")
print(df.describe())

print("")#

Q8
Rows and Columns:
(4, 3)
Column Names:
Index(['Name', 'Age', 'Score'], dtype='object')
Data Types:
Name     object
Age       int64
Score     int64
dtype: object
Statistical Summary:
             Age      Score
count   4.000000   4.000000
mean   21.500000  79.000000
std     1.290994  10.801234
min    20.000000  68.000000
25%    20.750000  71.000000
50%    21.500000  78.500000
75%    22.250000  86.500000
max    23.000000  91.000000

In [10]:
#Q9
print("Q9")
print(df.sort_values("Score", ascending=False))

print("")

Q9
    Name  Age  Score
2  Meera   20     91
0    Anu   21     85
1  Rahul   22     72
3   Arun   23     68

In [11]:
#Q10
df = pd.DataFrame({
    "Name": ["A", "B", "C", "D"],
    "Age": [21, np.nan, 23, 22],
    "Score": [80, 75, np.nan, 90]
})

print("Q10")

print("Missing Values:")
print(df.isnull().sum())

df["Age"] = df["Age"].fillna(df["Age"].mean())
df["Score"] = df["Score"].fillna(df["Score"].mean())

print("After filling missing values:")
print(df)

Q10
Missing Values:
Name     0
Age      1
Score    1
dtype: int64
After filling missing values:
  Name   Age      Score
0    A  21.0  80.000000
1    B  22.0  75.000000
2    C  23.0  81.666667
3    D  22.0  90.000000

In [24]:
import pandas as pd
import numpy as np




student_performance = pd.read_csv(
    "/content/drive/MyDrive/DSA/Dataset/numpy_pandas_assessment_datasets/student_performance.csv"
)



# Q11. Data Loading and Exploration

print("Q11")

print("First 5 records:")
print(student_performance.head())

print("")

print("Last 5 records:")
print(student_performance.tail())

print("")

print("Number of rows and columns:")
print(student_performance.shape)

print("")

print("Column names:")
print(student_performance.columns)

print("")

print("Data types:")
print(student_performance.dtypes)

print("")

print("Statistical summary:")
print(student_performance.describe())

print("\n")

Q11
First 5 records:
  Student_ID            Name  Gender        Department   Age  Attendance  \
0    STU1001     Rahul Varma    Male  Computer Science  25.0        74.7
1    STU1002    Kiran Pillai    Male  Computer Science  24.0        75.5
2    STU1003  Fathima Joseph  Female       Electronics  21.0        60.5
3    STU1004    Rahul Sharma  Female      Data Science  25.0        80.4
4    STU1005       Asha Nair  Female      Data Science  22.0        71.4

   Python_Score  SQL_Score  Pandas_Score  NumPy_Score  Final_Score
0          89.4       86.3          81.9         76.7         82.7
1          70.3       63.1          65.1         62.3         60.3
2          79.9       80.4          65.3         68.0         67.1
3          65.8       50.7          52.6         48.8         57.2
4          90.1       82.9          72.4         87.7         81.9

Last 5 records:
   Student_ID            Name  Gender        Department   Age  Attendance  \
75    STU1076     Priya Kumar  Female  Computer Science  24.0        99.3
76    STU1077      Amal Kumar    Male      Data Science   NaN        93.8
77    STU1078  Fathima Sharma    Male  Computer Science  19.0        86.4
78    STU1079    Meera Thomas    Male       Electronics  23.0        99.4
79    STU1080      Diya Varma    Male       Electronics  19.0        86.4

    Python_Score  SQL_Score  Pandas_Score  NumPy_Score  Final_Score
75          46.9       57.6          29.5         57.1         47.2
76          45.8       43.4          58.1         38.8         43.5
77          70.4       75.7          98.2         76.7         75.2
78          64.6       66.5          61.8         52.5         63.4
79          80.5       94.3          58.6         74.9         78.6

Number of rows and columns:
(80, 11)

Column names:
Index(['Student_ID', 'Name', 'Gender', 'Department', 'Age', 'Attendance',
       'Python_Score', 'SQL_Score', 'Pandas_Score', 'NumPy_Score',
       'Final_Score'],
      dtype='object')

Data types:
Student_ID       object
Name             object
Gender           object
Department       object
Age             float64
Attendance      float64
Python_Score    float64
SQL_Score       float64
Pandas_Score    float64
NumPy_Score     float64
Final_Score     float64
dtype: object

Statistical summary:
             Age  Attendance  Python_Score   SQL_Score  Pandas_Score  \
count  77.000000   77.000000     78.000000   80.000000     78.000000
mean   22.012987   81.672727     72.821795   70.445000     70.365385
std     2.155126   10.054204     16.722103   14.630417     15.814294
min    19.000000   56.300000     39.500000   38.300000     25.000000
25%    20.000000   75.500000     64.525000   60.650000     61.800000
50%    22.000000   81.100000     72.000000   69.300000     70.000000
75%    24.000000   86.400000     86.525000   81.150000     82.575000
max    25.000000  100.000000    100.000000  100.000000    100.000000

       NumPy_Score  Final_Score
count    78.000000    78.000000
mean     68.574359    70.696154
std      16.417242    14.053871
min      25.000000    40.600000
25%      57.175000    60.450000
50%      70.700000    70.950000
75%      80.650000    82.275000
max     100.000000    97.000000

In [26]:
# Q12 (1) Final Score > 75
print("Students with Final Score greater than 75:")
display(student_performance[student_performance["Final_Score"] > 75])


# Q12 (2) Attendance < 75%
print("Students with Attendance below 75%:")
display(student_performance[student_performance["Attendance"] < 75])


# Q12 (3) Data Science AND Final Score > 80
print("Data Science students with Final Score greater than 80:")
display(
    student_performance[
        (student_performance["Department"] == "Data Science") &
        (student_performance["Final_Score"] > 80)
    ]
)


# Q12 (4) Sort by Final Score
print("Students sorted by Final Score:")
display(
    student_performance.sort_values(
        by="Final_Score",
        ascending=False
    )
)

Students with Final Score greater than 75:

,Student_ID,Name,Gender,Department,Age,Attendance,Python_Score,SQL_Score,Pandas_Score,NumPy_Score,Final_Score
0,STU1001,Rahul Varma,Male,Computer Science,25.0,74.7,89.4,86.3,81.9,76.7,82.7
4,STU1005,Asha Nair,Female,Data Science,22.0,71.4,90.1,82.9,72.4,87.7,81.9
6,STU1007,Akhil Varma,Male,Electronics,22.0,73.2,81.7,82.2,81.5,64.2,77.0
7,STU1008,Akhil Varma,Male,Computer Science,20.0,81.1,72.1,80.4,72.9,73.5,79.2
8,STU1009,Diya Menon,Male,Data Science,25.0,64.4,94.8,86.0,87.7,100.0,83.0
10,STU1011,Diya Das,Female,Data Science,20.0,100.0,100.0,93.2,100.0,89.3,91.9
11,STU1012,Arun Reddy,Male,Electronics,20.0,69.1,80.4,78.0,88.9,77.1,86.9
16,STU1017,Rahul Thomas,Female,Data Science,25.0,78.3,80.8,99.4,77.2,100.0,91.1
17,STU1018,Priya Nair,Male,Data Science,19.0,85.4,62.6,81.6,79.6,75.5,75.1
23,STU1024,Fathima Joseph,Female,Commerce,23.0,78.2,87.7,71.0,88.5,74.8,83.7
24,STU1025,Kiran Varma,Female,Electronics,21.0,80.7,87.5,67.1,84.5,96.1,77.3
27,STU1028,Nikhil Nair,Female,Data Science,24.0,79.3,70.3,82.0,64.4,72.8,77.1
30,STU1031,Amal Varma,Female,Computer Science,19.0,86.7,86.9,64.3,100.0,89.2,85.5
33,STU1034,Amal Das,Male,Computer Science,19.0,85.5,94.4,81.6,71.3,81.5,84.3
35,STU1036,Maya Menon,Female,Electronics,19.0,82.0,95.3,93.4,100.0,62.5,84.2
37,STU1038,Kiran Pillai,Female,Electronics,25.0,85.2,87.8,78.3,85.5,82.7,82.4
39,STU1040,Rohan Sharma,Female,Computer Science,21.0,100.0,68.9,79.8,66.1,66.4,78.5
40,STU1041,Amal Pillai,Female,Computer Science,25.0,97.7,94.3,91.0,73.1,91.2,94.5
41,STU1042,Arun Joseph,Female,Computer Science,21.0,85.9,71.2,76.1,70.8,NaN,77.9
43,STU1044,Rahul Das,Female,Computer Science,22.0,70.9,68.0,67.3,83.6,76.7,77.3
47,STU1048,Priya Kumar,Male,Data Science,25.0,64.6,80.6,67.0,71.2,80.2,77.3
48,STU1049,Asha Sharma,Male,Data Science,22.0,91.3,88.9,95.0,NaN,94.5,97.0
51,STU1052,Gokul Nair,Female,Commerce,25.0,77.3,80.4,85.3,96.7,83.5,79.3
55,STU1056,Vivek Varma,Male,Data Science,22.0,81.0,87.0,95.1,88.4,75.7,93.3
56,STU1057,Rohan Pillai,Female,Commerce,20.0,79.5,72.1,66.9,61.8,72.3,75.2
57,STU1058,Diya Thomas,Female,Computer Science,23.0,83.5,93.1,78.8,91.6,83.8,92.3
58,STU1059,Anu Menon,Male,Electronics,24.0,96.7,99.7,77.1,68.9,89.7,84.9
59,STU1060,Asha Menon,Male,Data Science,19.0,56.3,100.0,85.0,87.4,57.4,87.9
61,STU1062,Kiran Pillai,Female,Computer Science,19.0,83.8,100.0,100.0,89.4,91.4,96.0
64,STU1065,Rohan Sharma,Male,Computer Science,19.0,64.4,96.5,69.3,86.7,80.7,83.5
67,STU1068,Maya Das,Female,Computer Science,23.0,66.7,83.4,79.6,89.3,83.6,83.7
73,STU1074,Anu Kumar,Female,Computer Science,22.0,95.0,95.3,67.7,92.4,81.4,83.4
77,STU1078,Fathima Sharma,Male,Computer Science,19.0,86.4,70.4,75.7,98.2,76.7,75.2
79,STU1080,Diya Varma,Male,Electronics,19.0,86.4,80.5,94.3,58.6,74.9,78.6

Students with Attendance below 75%:

,Student_ID,Name,Gender,Department,Age,Attendance,Python_Score,SQL_Score,Pandas_Score,NumPy_Score,Final_Score
0,STU1001,Rahul Varma,Male,Computer Science,25.0,74.7,89.4,86.3,81.9,76.7,82.7
2,STU1003,Fathima Joseph,Female,Electronics,21.0,60.5,79.9,80.4,65.3,68.0,67.1
4,STU1005,Asha Nair,Female,Data Science,22.0,71.4,90.1,82.9,72.4,87.7,81.9
6,STU1007,Akhil Varma,Male,Electronics,22.0,73.2,81.7,82.2,81.5,64.2,77.0
8,STU1009,Diya Menon,Male,Data Science,25.0,64.4,94.8,86.0,87.7,100.0,83.0
9,STU1010,Gokul Pillai,Female,Computer Science,19.0,67.3,79.6,85.0,74.1,80.5,73.8
11,STU1012,Arun Reddy,Male,Electronics,20.0,69.1,80.4,78.0,88.9,77.1,86.9
15,STU1016,Nikhil Kumar,Female,Computer Science,NaN,70.3,55.9,69.3,67.1,58.4,58.2
19,STU1020,Vivek Sharma,Female,Commerce,22.0,72.1,65.8,60.9,49.8,44.8,54.6
25,STU1026,Maya Menon,Male,Electronics,20.0,68.3,91.7,64.5,83.5,73.7,69.4
36,STU1037,Nikhil Menon,Male,Electronics,22.0,74.8,69.5,60.7,64.6,81.6,69.1
42,STU1043,Sneha Varma,female,Data Science,19.0,74.4,71.8,79.1,69.8,95.9,NaN
43,STU1044,Rahul Das,Female,Computer Science,22.0,70.9,68.0,67.3,83.6,76.7,77.3
47,STU1048,Priya Kumar,Male,Data Science,25.0,64.6,80.6,67.0,71.2,80.2,77.3
50,STU1051,Gokul Menon,Male,Data Science,25.0,70.9,68.6,81.0,64.0,63.0,70.5
59,STU1060,Asha Menon,Male,Data Science,19.0,56.3,100.0,85.0,87.4,57.4,87.9
64,STU1065,Rohan Sharma,Male,Computer Science,19.0,64.4,96.5,69.3,86.7,80.7,83.5
67,STU1068,Maya Das,Female,Computer Science,23.0,66.7,83.4,79.6,89.3,83.6,83.7
71,STU1072,Vivek Pillai,Male,Commerce,24.0,71.5,59.0,58.2,56.3,48.9,56.6

Data Science students with Final Score greater than 80:

,Student_ID,Name,Gender,Department,Age,Attendance,Python_Score,SQL_Score,Pandas_Score,NumPy_Score,Final_Score
4,STU1005,Asha Nair,Female,Data Science,22.0,71.4,90.1,82.9,72.4,87.7,81.9
8,STU1009,Diya Menon,Male,Data Science,25.0,64.4,94.8,86.0,87.7,100.0,83.0
10,STU1011,Diya Das,Female,Data Science,20.0,100.0,100.0,93.2,100.0,89.3,91.9
16,STU1017,Rahul Thomas,Female,Data Science,25.0,78.3,80.8,99.4,77.2,100.0,91.1
48,STU1049,Asha Sharma,Male,Data Science,22.0,91.3,88.9,95.0,NaN,94.5,97.0
55,STU1056,Vivek Varma,Male,Data Science,22.0,81.0,87.0,95.1,88.4,75.7,93.3
59,STU1060,Asha Menon,Male,Data Science,19.0,56.3,100.0,85.0,87.4,57.4,87.9

Students sorted by Final Score:

,Student_ID,Name,Gender,Department,Age,Attendance,Python_Score,SQL_Score,Pandas_Score,NumPy_Score,Final_Score
48,STU1049,Asha Sharma,Male,Data Science,22.0,91.3,88.9,95.0,NaN,94.5,97.0
61,STU1062,Kiran Pillai,Female,Computer Science,19.0,83.8,100.0,100.0,89.4,91.4,96.0
40,STU1041,Amal Pillai,Female,Computer Science,25.0,97.7,94.3,91.0,73.1,91.2,94.5
55,STU1056,Vivek Varma,Male,Data Science,22.0,81.0,87.0,95.1,88.4,75.7,93.3
57,STU1058,Diya Thomas,Female,Computer Science,23.0,83.5,93.1,78.8,91.6,83.8,92.3
...,...,...,...,...,...,...,...,...,...,...,...
34,STU1035,Rahul Pillai,Female,Data Science,22.0,82.5,41.4,44.4,53.8,43.2,44.2
76,STU1077,Amal Kumar,Male,Data Science,NaN,93.8,45.8,43.4,58.1,38.8,43.5
26,STU1027,Aditya Pillai,Female,Computer Science,25.0,79.6,44.0,52.5,25.0,25.0,40.6
42,STU1043,Sneha Varma,female,Data Science,19.0,74.4,71.8,79.1,69.8,95.9,NaN
53,STU1054,Maya Sharma,Male,Data Science,19.0,82.5,59.7,60.5,65.8,73.3,NaN

In [27]:

# Q13. Feature Creation


print("Q13")

student_performance["Average_Technical_Score"] = (
    student_performance[
        [
            "Python_Score",
            "SQL_Score",
            "Pandas_Score",
            "NumPy_Score"
        ]
    ].mean(axis=1)
)

student_performance["Performance"] = pd.cut(
    student_performance["Average_Technical_Score"],
    bins=[-np.inf, 60, 75, 90, np.inf],
    labels=[
        "Needs Improvement",
        "Average",
        "Good",
        "Excellent"
    ],
    right=False
)

print(student_performance)

print("\n")

Q13
   Student_ID            Name  Gender        Department   Age  Attendance  \
0     STU1001     Rahul Varma    Male  Computer Science  25.0        74.7
1     STU1002    Kiran Pillai    Male  Computer Science  24.0        75.5
2     STU1003  Fathima Joseph  Female       Electronics  21.0        60.5
3     STU1004    Rahul Sharma  Female      Data Science  25.0        80.4
4     STU1005       Asha Nair  Female      Data Science  22.0        71.4
..        ...             ...     ...               ...   ...         ...
75    STU1076     Priya Kumar  Female  Computer Science  24.0        99.3
76    STU1077      Amal Kumar    Male      Data Science   NaN        93.8
77    STU1078  Fathima Sharma    Male  Computer Science  19.0        86.4
78    STU1079    Meera Thomas    Male       Electronics  23.0        99.4
79    STU1080      Diya Varma    Male       Electronics  19.0        86.4

    Python_Score  SQL_Score  Pandas_Score  NumPy_Score  Final_Score  \
0           89.4       86.3          81.9         76.7         82.7
1           70.3       63.1          65.1         62.3         60.3
2           79.9       80.4          65.3         68.0         67.1
3           65.8       50.7          52.6         48.8         57.2
4           90.1       82.9          72.4         87.7         81.9
..           ...        ...           ...          ...          ...
75          46.9       57.6          29.5         57.1         47.2
76          45.8       43.4          58.1         38.8         43.5
77          70.4       75.7          98.2         76.7         75.2
78          64.6       66.5          61.8         52.5         63.4
79          80.5       94.3          58.6         74.9         78.6

    Average_Technical_Score        Performance
0                    83.575               Good
1                    65.200            Average
2                    73.400            Average
3                    54.475  Needs Improvement
4                    83.275               Good
..                      ...                ...
75                   47.775  Needs Improvement
76                   46.525  Needs Improvement
77                   80.250               Good
78                   61.350            Average
79                   77.075               Good

[80 rows x 13 columns]

In [28]:

# Q14. GroupBy Analysis


print(" Q14 ")

department_result = student_performance.groupby(
    "Department"
).agg(
    Number_of_Students=("Student_ID", "count"),
    Average_Final_Score=("Final_Score", "mean"),
    Maximum_Final_Score=("Final_Score", "max"),
    Minimum_Final_Score=("Final_Score", "min")
)

department_result = department_result.sort_values(
    by="Average_Final_Score",
    ascending=False
)

print(department_result)

print("\n")

 Q14
                  Number_of_Students  Average_Final_Score  \
Department
Electronics                       13            72.846154
Computer Science                  29            71.479310
Data Science                      27            71.324000
Commerce                           8            67.825000
data science                       1            66.900000
 Data Science                      1            55.100000
Computer science                   1            46.700000

                  Maximum_Final_Score  Minimum_Final_Score
Department
Electronics                      86.9                 51.2
Computer Science                 96.0                 40.6
Data Science                     97.0                 43.5
Commerce                         83.7                 54.6
data science                     66.9                 66.9
 Data Science                    55.1                 55.1
Computer science                 46.7                 46.7

In [32]:

# Q15. NumPy and Pandas Integration


print(" Q15 ")

scores = student_performance['Final_Score'].dropna().values

print("Mean:", scores.mean())
print("Median:", np.median(scores))
print("Std:", scores.std())
print("25th Percentile:", np.percentile(scores, 25))
print("75th Percentile:", np.percentile(scores, 75))


print(student_performance[student_performance['Final_Score'] > scores.mean()])

 Q15
Mean: 70.69615384615383
Median: 70.95
Std: 13.96349124578818
25th Percentile: 60.449999999999996
75th Percentile: 82.275
   Student_ID            Name  Gender        Department   Age  Attendance  \
0     STU1001     Rahul Varma    Male  Computer Science  25.0        74.7
4     STU1005       Asha Nair  Female      Data Science  22.0        71.4
6     STU1007     Akhil Varma    Male       Electronics  22.0        73.2
7     STU1008     Akhil Varma    Male  Computer Science  20.0        81.1
8     STU1009      Diya Menon    Male      Data Science  25.0        64.4
9     STU1010    Gokul Pillai  Female  Computer Science  19.0        67.3
10    STU1011        Diya Das  Female      Data Science  20.0       100.0
11    STU1012      Arun Reddy    Male       Electronics  20.0        69.1
16    STU1017    Rahul Thomas  Female      Data Science  25.0        78.3
17    STU1018      Priya Nair    Male      Data Science  19.0        85.4
20    STU1021      Arun Varma  Female          Commerce  25.0        79.5
23    STU1024  Fathima Joseph  Female          Commerce  23.0        78.2
24    STU1025     Kiran Varma  Female       Electronics  21.0        80.7
27    STU1028     Nikhil Nair  Female      Data Science  24.0        79.3
30    STU1031      Amal Varma  Female  Computer Science  19.0        86.7
33    STU1034        Amal Das    Male  Computer Science  19.0        85.5
35    STU1036      Maya Menon  Female       Electronics  19.0        82.0
37    STU1038    Kiran Pillai  Female       Electronics  25.0        85.2
39    STU1040    Rohan Sharma  Female  Computer Science  21.0       100.0
40    STU1041     Amal Pillai  Female  Computer Science  25.0        97.7
41    STU1042     Arun Joseph  Female  Computer Science  21.0        85.9
43    STU1044       Rahul Das  Female  Computer Science  22.0        70.9
46    STU1047       Gokul Das    Male      Data Science  21.0         NaN
47    STU1048     Priya Kumar    Male      Data Science  25.0        64.6
48    STU1049     Asha Sharma    Male      Data Science  22.0        91.3
51    STU1052      Gokul Nair  Female          Commerce  25.0        77.3
52    STU1053      Maya Varma    Male  Computer Science  22.0        84.6
55    STU1056     Vivek Varma    Male      Data Science  22.0        81.0
56    STU1057    Rohan Pillai  Female          Commerce  20.0        79.5
57    STU1058     Diya Thomas  Female  Computer Science  23.0        83.5
58    STU1059       Anu Menon    Male       Electronics  24.0        96.7
59    STU1060      Asha Menon    Male      Data Science  19.0        56.3
60    STU1061  Fathima Sharma    Male  Computer Science  24.0        79.6
61    STU1062    Kiran Pillai  Female  Computer Science  19.0        83.8
64    STU1065    Rohan Sharma    Male  Computer Science  19.0        64.4
66    STU1067    Rahul Thomas    Male      Data Science   NaN        99.3
67    STU1068        Maya Das  Female  Computer Science  23.0        66.7
72    STU1073   Swathi Joseph    Male      Data Science  22.0        78.7
73    STU1074       Anu Kumar  Female  Computer Science  22.0        95.0
74    STU1075      Gokul Nair  Female      Data Science  23.0        87.8
77    STU1078  Fathima Sharma    Male  Computer Science  19.0        86.4
79    STU1080      Diya Varma    Male       Electronics  19.0        86.4

    Python_Score  SQL_Score  Pandas_Score  NumPy_Score  Final_Score  \
0           89.4       86.3          81.9         76.7         82.7
4           90.1       82.9          72.4         87.7         81.9
6           81.7       82.2          81.5         64.2         77.0
7           72.1       80.4          72.9         73.5         79.2
8           94.8       86.0          87.7        100.0         83.0
9           79.6       85.0          74.1         80.5         73.8
10         100.0       93.2         100.0         89.3         91.9
11          80.4       78.0          88.9         77.1         86.9
16          80.8       99.4          77.2        100.0         91.1
17          62.6       81.6          79.6         75.5         75.1
20           NaN       67.6          74.3         75.3         73.2
23          87.7       71.0          88.5         74.8         83.7
24          87.5       67.1          84.5         96.1         77.3
27          70.3       82.0          64.4         72.8         77.1
30          86.9       64.3         100.0         89.2         85.5
33          94.4       81.6          71.3         81.5         84.3
35          95.3       93.4         100.0         62.5         84.2
37          87.8       78.3          85.5         82.7         82.4
39          68.9       79.8          66.1         66.4         78.5
40          94.3       91.0          73.1         91.2         94.5
41          71.2       76.1          70.8          NaN         77.9
43          68.0       67.3          83.6         76.7         77.3
46          69.5       59.3          75.2         75.2         74.8
47          80.6       67.0          71.2         80.2         77.3
48          88.9       95.0           NaN         94.5         97.0
51          80.4       85.3          96.7         83.5         79.3
52          71.9       73.4          70.0         67.2         71.0
55          87.0       95.1          88.4         75.7         93.3
56          72.1       66.9          61.8         72.3         75.2
57          93.1       78.8          91.6         83.8         92.3
58          99.7       77.1          68.9         89.7         84.9
59         100.0       85.0          87.4         57.4         87.9
60          80.8       63.1          71.1         67.9         70.8
61         100.0      100.0          89.4         91.4         96.0
64          96.5       69.3          86.7         80.7         83.5
66           NaN       56.2          69.0         81.5         70.7
67          83.4       79.6          89.3         83.6         83.7
72          76.4       77.5          73.6         65.6         73.5
73          95.3       67.7          92.4         81.4         83.4
74          85.4       80.0          65.2         70.4         70.9
77          70.4       75.7          98.2         76.7         75.2
79          80.5       94.3          58.6         74.9         78.6

    Average_Technical_Score Performance
0                    83.575        Good
4                    83.275        Good
6                    77.400        Good
7                    74.725     Average
8                    92.125   Excellent
9                    79.800        Good
10                   95.625   Excellent
11                   81.100        Good
16                   89.350        Good
17                   74.825     Average
20                   72.400     Average
23                   80.500        Good
24                   83.800        Good
27                   72.375     Average
30                   85.100        Good
33                   82.200        Good
35                   87.800        Good
37                   83.575        Good
39                   70.300     Average
40                   87.400        Good
41                   72.700     Average
43                   73.900     Average
46                   69.800     Average
47                   74.750     Average
48                   92.800   Excellent
51                   86.475        Good
52                   70.625     Average
55                   86.550        Good
56                   68.275     Average
57                   86.825        Good
58                   83.850        Good
59                   82.450        Good
60                   70.725     Average
61                   95.200   Excellent
64                   83.300        Good
66                   68.900     Average
67                   83.975        Good
72                   73.275     Average
73                   84.200        Good
74                   75.250        Good
77                   80.250        Good
79                   77.075        Good

In [37]:
#Q18
import pandas as pd
import numpy as np

df = pd.read_csv('/content/drive/MyDrive/DSA/Dataset/numpy_pandas_assessment_datasets/employee.csv')


df['Salary'] = pd.to_numeric(df['Salary'], errors='coerce')
df['Experience'] = pd.to_numeric(df['Experience'], errors='coerce')

#A. NumPy Analysis
salary = df['Salary'].dropna().values
perf = df['Performance_Score'].dropna().values

print("Mean Salary:", salary.mean())
print("Median Salary:", np.median(salary))
print("Std Salary:", salary.std())
print("Mean Performance:", perf.mean())

Mean Salary: 60809.281690140844
Median Salary: 61196.0
Std Salary: 18154.72754492641
Mean Performance: 71.01369863013699

In [38]:
#Q18
#B. Filtering
filtered = df[(df['Experience'] > 3) & (df['Performance_Score'] >= 80)]
print(filtered)

   Employee_ID            Department  Experience   Salary  Performance_Score  \
1      EMP2002  Software Development         8.7  78243.0               85.6
6      EMP2007                    HR         4.6  51328.0               91.0
17     EMP2018  Software development         5.6  79595.0               83.0
22     EMP2023        Data Analytics         5.7  83674.0               81.0
25     EMP2026      Data Engineering         5.8  45336.0               88.0
26     EMP2027  Software Development         8.1  74816.0               84.3
30     EMP2031  Software Development         6.9  60930.0               94.4
31     EMP2032            IT Support         4.7  65566.0               85.7
45     EMP2046  Software Development         3.4  51056.0               92.8
48     EMP2049      Data Engineering         4.7  43341.0               82.2
49     EMP2050  Software Development         4.9  68620.0               90.9
57     EMP2058                    HR         5.3  68152.0               81.1
58     EMP2059      Data Engineering         3.8  52079.0               84.1
62     EMP2063  Software Development         7.0  74892.0               88.0
65     EMP2066  Software Development         5.9  82567.0               81.1
69     EMP2070            IT Support         3.1  60755.0               83.4
72     EMP2073      Data Engineering         8.3  83685.0               87.4
74     EMP2075  Software Development        10.1  98224.0               83.6

    Projects_Completed
1                 11.0
6                  0.0
17                 9.0
22                12.0
25                 NaN
26                19.0
30                 6.0
31                 6.0
45                 2.0
48                 5.0
49                11.0
57                 6.0
58                 7.0
62                15.0
65                10.0
69                 1.0
72                16.0
74                13.0

In [39]:
#Q18
#C. Department Analysis
dept_summary = df.groupby('Department').agg(
    Average_Salary=('Salary', 'mean'),
    Average_Performance=('Performance_Score', 'mean'),
    Total_Projects=('Projects_Completed', 'sum'),
    Employee_Count=('Employee_ID', 'count')
)
print(dept_summary)
print("Highest Performance Dept:", dept_summary['Average_Performance'].idxmax())

                      Average_Salary  Average_Performance  Total_Projects  \
Department
 data analytics         46324.000000            73.800000             6.0
Data Analytics          56936.066667            67.176471           108.0
Data Engineering        60109.916667            72.130769            73.0
HR                      63136.300000            64.900000            47.0
IT Support              64330.500000            70.416667            30.0
Software Development    61269.840000            74.933333           190.0
Software development    79595.000000            83.000000             9.0

                      Employee_Count
Department
 data analytics                    1
Data Analytics                    17
Data Engineering                  13
HR                                10
IT Support                         7
Software Development              25
Software development               1
Highest Performance Dept: Software development

In [40]:
#Q18
#D. Analytical Interpretation
flagged = df[(df['Salary'] > salary.mean()) & (df['Performance_Score'] < perf.mean())]
print(flagged[['Employee_ID', 'Department', 'Salary', 'Performance_Score']])

   Employee_ID            Department   Salary  Performance_Score
0      EMP2001                    HR  76776.0               57.7
7      EMP2008        Data Analytics  70881.0               67.9
12     EMP2013      Data Engineering  68546.0               51.6
13     EMP2014  Software Development  67786.0               51.7
27     EMP2028                    HR  68128.0               56.3
41     EMP2042        Data Analytics  96565.0               70.1
42     EMP2043  Software Development  82170.0               67.3
43     EMP2044                    HR  66053.0               52.6
47     EMP2048            IT Support  66074.0               54.7
52     EMP2053                    HR  64357.0               47.2
60     EMP2061  Software Development  83576.0               63.1
64     EMP2065                    HR  61142.0               52.3
66     EMP2067        Data Analytics  61196.0               65.9
67     EMP2068  Software Development  73254.0               66.0
73     EMP2074      Data Engineering  84323.0               63.5

In [42]:
#Q17

df = pd.read_csv('/content/drive/MyDrive/DSA/Dataset/numpy_pandas_assessment_datasets/sales.csv')


df['Order_Date'] = pd.to_datetime(df['Order_Date'], errors='coerce')
df['Sales'] = pd.to_numeric(df['Sales'], errors='coerce')
df['Discount'] = pd.to_numeric(df['Discount'], errors='coerce')


df['Quantity'] = df['Quantity'].fillna(df['Quantity'].median())
df['Profit'] = df['Profit'].fillna(df['Profit'].median())
df['Sales'] = df['Sales'].fillna(df['Sales'].median())
df['Discount'] = df['Discount'].fillna(df['Discount'].mean())
df['Region'] = df['Region'].fillna('Unknown').str.strip().str.title()
df['Category'] = df['Category'].str.strip().str.title()

In [46]:
#Q17
#B. Sales Analysis
total_sales = df['Sales'].sum()
total_profit = df['Profit'].sum()
avg_sales = df['Sales'].mean()

top_5_products = df.groupby('Product')['Sales'].sum().nlargest(5)
top_region = df.groupby('Region')['Sales'].sum().idxmax()

print(f"Total Sales: {total_sales:.2f}")
print(f"Total Profit: {total_profit:.2f}")
print(f"Average Sales: {avg_sales:.2f}")
print("Top 5 Products:\n", top_5_products)
print("Region with Highest Sales:", top_region)

Total Sales: 93383.94
Total Profit: 15201.35
Average Sales: 518.80
Top 5 Products:
 Product
Laptop        33995.0
Printer       13719.3
Tablet        10291.2
Monitor        8492.4
Headphones     5999.5
Name: Sales, dtype: float64
Region with Highest Sales: West

In [45]:
#Q17
#C. Category Analysis
cat_summary = df.groupby('Category').agg(
    Total_Sales=('Sales', 'sum'),
    Total_Profit=('Profit', 'sum'),
    Average_Discount=('Discount', 'mean')
).sort_values(by='Total_Sales', ascending=False)

print("\nCategory Summary:\n", cat_summary)

Category Summary:
                   Total_Sales  Total_Profit  Average_Discount
Category
Computers            53930.60       8971.75          0.063514
Office Equipment     13719.30       2176.64          0.058421
Accessories          13088.28       2133.48          0.077764
Furniture             7329.46       1113.32          0.074815
Storage               5316.30        806.16          0.075385